name: Publish Artifacts
on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "IridiumCore"
          path: "build/libs/IridiumCore-*.jar"

  update-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Downloading artifact
        uses: actions/checkout@v4
      - uses: thecodemonkey/action-get-gradle-version@master
        id: version
        with:
          file: "build.gradle.kts"
      - uses: actions/download-artifact@v4.3.0
        with:
          name: "IridiumCore"
          path: "./"

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: "IridiumCore-*.jar"

  publish-nexus:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: thecodemonkey/action-get-gradle-version@master
        id: version
        with:
          file: "build.gradle.kts"

      - name: Download build artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: "IridiumCore"
          path: "./"

      - name: Find IridiumCore jar
        id: find_jar
        run: |
          FILE=$(find . -type f -name "IridiumCore-*.jar" | head -n 1)
          echo "file=$FILE" >> "$GITHUB_OUTPUT"

      - name: Upload to Nexus with curl
        run: |
          curl --location 'https://nexus.iridiumdevelopment.net/service/rest/v1/components?repository=maven-releases' \
          --header 'Authorization: Basic ${{ secrets.NEXUS_AUTH }}' \
          -F "maven2.groupId=com.iridium" \
          -F "maven2.artifactId=IridiumCore" \
          -F "maven2.version=${{ steps.version.outputs.version }}" \
          -F "maven2.generate-pom=true" \
          -F "maven2.asset1=@${{ steps.find_jar.outputs.file }}" \
          -F "maven2.asset1.extension=jar"