name: Publish Artifacts
on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3.0.0
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload artifacts
        uses: "actions/upload-artifact@v2.2.3"
        with:
          name: "IridiumCore"
          path: "build/libs/IridiumCore-*.jar"

  update-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Downloading artifact
        uses: actions/checkout@v2
      - uses: thecodemonkey/action-get-gradle-version@master
        id: version
        with:
          file: "build.gradle.kts"
      - uses: actions/download-artifact@v3.0.2
        with:
          name: "IridiumCore"
          path: "./"

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: "IridiumCore-*.jar"

  publish-nexus:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Downloading artifact
        uses: actions/checkout@v2
      - uses: thecodemonkey/action-get-gradle-version@master
        id: version
        with:
          file: "build.gradle.kts"
      - uses: actions/download-artifact@v3.0.2
        with:
          name: "IridiumCore"
          path: "./"

      - name: Publishing to Nexus
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: "https://nexus.iridiumdevelopment.net/"
          username: "${{ secrets.NEXUS_USERNAME }}"
          password: "${{ secrets.NEXUS_PASSWORD }}"
          format: "maven2"
          repository: "maven-releases"
          coordinates: "groupId=com.iridium artifactId=IridiumCore version=${{steps.version.outputs.version}} generate-pom=on"
          assets: "extension=jar"
          filename: "IridiumCore-*.jar"